// Curated top-50 games across all platforms (PC, console, mobile).
// Order = featured_rank. Seeded into the DB via npm run seed:top50.

export const TOP50: string[] = [
  "Minecraft",
  "Grand Theft Auto V",
  "The Legend of Zelda: Breath of the Wild",
  "Elden Ring",
  "The Witcher 3: Wild Hunt",
  "Red Dead Redemption 2",
  "Baldur's Gate 3",
  "The Last of Us",
  "God of War (2018)",
  "Super Mario Odyssey",
  "Tetris",
  "Dark Souls",
  "Hollow Knight",
  "Hades",
  "Celeste",
  "Portal 2",
  "Half-Life 2",
  "The Elder Scrolls V: Skyrim",
  "Fortnite",
  "League of Legends",
  "Dota 2",
  "Counter-Strike 2",
  "Valorant",
  "Apex Legends",
  "Overwatch 2",
  "World of Warcraft",
  "StarCraft II",
  "Civilization VI",
  "Factorio",
  "Stardew Valley",
  "Terraria",
  "Rocket League",
  "Sekiro: Shadows Die Twice",
  "Bloodborne",
  "Ghost of Tsushima",
  "Cyberpunk 2077",
  "Doom Eternal",
  "Resident Evil 4",
  "Metal Gear Solid V: The Phantom Pain",
  "Mass Effect 2",
  "BioShock",
  "Super Smash Bros. Ultimate",
  "Mario Kart 8 Deluxe",
  "Animal Crossing: New Horizons",
  "The Legend of Zelda: Tears of the Kingdom",
  "Genshin Impact",
  "Street Fighter 6",
  "Monster Hunter: World",
  "Disco Elysium",
  "Slay the Spire",
];
